# Generated by Django 4.2.5 on 2023-09-04 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=150)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=150)),
                ('nome_empresa', models.CharField(max_length=150)),
                ('categoria_empresa', models.CharField(max_length=150)),
                ('quitado', models.BooleanField(default=False)),
                ('imagem', models.FileField(default=False, upload_to='')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_localizacao', to='reservas.stand')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_valor', to='reservas.stand')),
            ],
        ),
    ]
