# Generated by Django 4.2.5 on 2023-10-03 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservas",
            "0002_alter_reserva_categoria_empresa_alter_reserva_cnpj_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="reserva",
            old_name="localizacao",
            new_name="stand",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="valor",
        ),
    ]
